#!/usr/bin/env node

var Node = {
  fs: require('fs'),
  process: process
};

var ZIP = require('.');

var file = Node.process.argv[2];
if (file === undefined) return console.error('usage: ./decode <file>');

try {
  var buffer = Node.fs.readFileSync(file);
  var headers = ZIP.decode(buffer);
  headers.forEach(
    function(header) {
      console.log(header);
    }
  );
} catch (error) {
  console.error(error.message || error);
}
